#!/bin/bash
# Bundles the per-language Tuvora.strings generated by :tvosCore:generateTvosResources from the shared
# composeResources XML, so getString() on Apple TV resolves in the user's language.
set -euo pipefail
SRC="$SRCROOT/../tvosCore/build/generated/tvosResources/lproj"
DEST="$TARGET_BUILD_DIR/$UNLOCALIZED_RESOURCES_FOLDER_PATH"
[ -d "$SRC" ] || { echo "error: $SRC missing - the Kotlin build step did not generate string tables" >&2; exit 1; }
for dir in "$SRC"/*.lproj; do
  name=$(basename "$dir"); [ "$name" = "Base.lproj" ] && name="en.lproj"
  mkdir -p "$DEST/$name"; cp "$dir/Tuvora.strings" "$DEST/$name/Tuvora.strings"
done
